### ISSUE TITLE
Bitwise OR "|" operator, causes backward compatibility issues 

### ISSUE THREAD

**Issue by JanoschMenke** [EBjerrum/rdeditor#9]
So I noticed that if you use older Pyside2 versions for example 13.x.x. Bitwise operators like `&` and `|`, will cause issues like so:

```
TypeError: 'PySide2.QtWidgets.QMessageBox.StandardButton' object cannot be interpreted as an integer
```

So maybe to ensure backward compatibility ones can switch this to `or`

**Comment by EBjerrum** [comment]
Ah, thanks for the explanation. It depends on the version of PySide. I'm using a later version, but have noted that that version gets installed with newer versions of python. We can fix this now, but Pyside2 seems to be a burning platform. I wonder how much needs to be changed to switch to a newer.

**Comment by JanoschMenke** [comment]
Yeah same here. On my old environment I can have Python 3.11 with PySide2 15.x.x. I now set up a new envs with Python 3.11. And now I can't install PySide2 15.x.x due to the Python requirements of PySide2 15.

**Comment by EBjerrum** [comment]
Fixed with new release 0.1.3.8

**Comment by EBjerrum** [comment]
But it's a bit weird that a newer python installs an older pyside....

**Comment by JanoschMenke** [comment]
Hi so the or operator does not solve the issue either, to be honest I do not really understand the issue. But I will let you know ones i figured it out

**Comment by EBjerrum** [comment]
It did in my test in python 3.11 with the older pyside2. So yeah, let me know what you find out.

Yahoo Mail: Søg, organiser, behersk 
 
   På man., den 15. apr. 2024 klokken 17:07, Janosch ***@***.***> skrev:   


Hi so the or operator does not solve the issue either, to be honest I do not really understand the issue. But I will let you know ones i figured it out

**Comment by JanoschMenke** [comment]
Hi Esben,

I fail to reproduce the error:
but a simple solution can be:
```
userInfo = QMessageBox.question(self, title, msg)
```

by default the Yes and No Button will be included
